# [Обязательное] Название сайта
site_name: columba-docs

# Базовый адрес сайта
site_url: https://lencodigitexer.github.io/columba-docs/

# Описание сайта. Добавляется в meta в html-заголовке каждой страницы.
site_description: Documentation for messenger "columba"

# Автор (или авторы) сайта. Добавляется в html-заголовок каждой страницы.
site_author: Dzhigit

# Ссылка на репозиторий, в котором хранятся исходные материалы.
repo_url: https://github.com/LencoDigitexer/columba-docs

# Относительный путь, который в сочетании со ссылкой на репозиторий (repo_url)
# и относительным адресом страницы даст адрес, по которому можно вызвать
# редактор страницы. Для repo_url-ов известных площадок (например,
# GitHub или GitLab можно оставить пустым - он подставится автоматически)
edit_uri: ""

# Информация о теме, которая будет применена для сгенерированного сайта.
# И её параметрах
theme:
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - django

# Структура навигации генерируемого сайта.
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Overview: user-guide/index.md
      - Installation: user-guide/installation.md
      - Writing Your Docs: user-guide/writing-your-docs.md
      - Choosing Your Theme: user-guide/choosing-your-theme.md
      - Customizing Your Theme: user-guide/customizing-your-theme.md
      - Localizing Your Theme: user-guide/localizing-your-theme.md
      - Configuration: user-guide/configuration.md
      - Deploying Your Docs: user-guide/deploying-your-docs.md
  - Developer Guide:
      - Overview: dev-guide/index.md
      - Themes: dev-guide/themes.md
      - Translations: dev-guide/translations.md
      - Plugins: dev-guide/plugins.md
  - About:
      - Release Notes: about/release-notes.md
      - Contributing: about/contributing.md
      - License: about/license.md

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2024 <a href="https://github.com/Dzhigit/columba">columba.</a>.
